	tilepal 0, TEXT, GRAY, GREEN, RED, TEXT, GREEN, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GRAY, GRAY, BROWN, RED, RED, RED, RED
	tilepal 0, ROOF, ROOF, ROOF, GRAY, GRAY, BROWN, GRAY, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GRAY, ROOF, ROOF, TEXT, TEXT
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GRAY, ROOF, TEXT
